language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r Lotto *
  - mkdir -p deploy
  - mv Lotto.zip deploy/Lotto.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jutudy-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jutudy-springboot-build
    key: jutudy-springboot-webservice.zip
    bundle_type: zip
    application: jutudy-springboot-webservice
    deployment_group: jutudy-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jutudy.js@gmail.com